language: rust

cache: cargo

jobs:
  # Allow nightly failures / don't wait for nightly to finish build
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - name: "build and test workspace, format code - stable"
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - cargo fmt --all -- --check

    - name: "build and test workspace - beta"
      rust: beta
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all

    - name: "build and test workspace - nightly"
      rust: nightly
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all

    - name: "build web-client / wasm-bindgen - stable"
      rust: stable
      install:
        - rustup target add wasm32-unknown-unknown
      script:
        -  ./web-client/build.sh

