[package]
name = "expr_to_geom"
version = "0.1.0"
authors = ["Sally Soul <SallySoul@protonmail.com>"]
edition = "2018"

[dependencies]
implicit-mesh = { path = "../implicit-mesh"}
geoprim = { path = "../geoprim" }
structopt = "0.2.8"
bincode = "1.0.0"
